/**
 * @fileoverview This file contains a class for working with keyboard events
 * that repeat consistently across browsers and platforms. It also unifies the
 * key code so that it is the same in all browsers and platforms.
 *
 * @modified Leo.Zhang
 * @email zmike86@gmail.com
 * @see ../demos/keyhandler.html
 */

sogou('Sogou.Events.KeyEvent',
    [
        'Sogou.Util',
        'Sogou.Events.BrowserEvent',
        'Sogou.Events.KeyEventType'
    ],
    function(util, BrowserEvent, KeyEventType) {

        'use strict';

        /**
         * This class is used for the KeyEventType.KEY event and
         * it overrides the key code with the fixed key code.
         * @param {number} keyCode The adjusted key code.
         * @param {number} charCode The unicode character code.
         * @param {boolean} repeat Whether this event was generated by keyboard repeat.
         * @param {Event} browserEvent Browser event object.
         * @constructor
         * @extends {BrowserEvent}
         */
        var KeyEvent = function(keyCode, charCode, repeat, browserEvent) {
            BrowserEvent.call(this, browserEvent);
            this.type = KeyEventType.KEY;

            /**
             * Keycode of key press.
             * @type {number}
             */
            this.keyCode = keyCode;

            /**
             * Unicode character code.
             * @type {number}
             */
            this.charCode = charCode;

            /**
             * True if this event was generated by keyboard auto-repeat (i.e., the user is
             * holding the key down.)
             * @type {boolean}
             */
            this.repeat = repeat;
        };
        util.inherits(KeyEvent, BrowserEvent);

        return KeyEvent;
    }
);
